### ISSUE TITLE
Dafny-to-Rust code generator

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5561]
Here is a tracking of the issues that a fully working Dafny-to-Rust code generator will have to solve:

- [ ] https://github.com/dafny-lang/dafny/issues/601 - close when new arrays are merged
- [ ] https://github.com/dafny-lang/dafny/issues/5200
- [ ] https://github.com/dafny-lang/dafny/issues/5203 - close when the part of the branch that does not emit runtime is merged.
- [ ] https://github.com/dafny-lang/dafny/issues/5321
- [ ] https://github.com/dafny-lang/dafny/issues/5537
- [ ] https://github.com/dafny-lang/dafny/issues/5560 (when all is finished)
